services:
  wordpress:
    container_name: SITE_NAME
    image: 'ghcr.io/boost-creative/coolify-wordpress-8'
    restart: unless-stopped
    cpus: '3'
    mem_limit: 1024m
    depends_on:
      - mariadb
      - valkey
    volumes:
      - '/home/sites/boost/SITE_NAME/wordpress:/usr/src/wordpress'
      - '/home/sites/boost/SITE_NAME/db:/var/db'
      - 'sock:/tmp/sock:ro'
    environment:
      TZ: America/Detroit
      DB_HOST: 'localhost:/tmp/sock/mysqld.sock'
      REDIS_HOST: /tmp/sock/valkey.sock
      ADDITIONAL_PLUGINS: 'w3-total-cache fluent-smtp better-wp-security simple-cloudflare-turnstile'
      MDBU: '${SERVICE_USER_MARIADB}'
      MDBP: '${SERVICE_PASSWORD_MARIADB}'
      CRON: |
        8 2 * * * sleep $(tr -dc 0-9 < /dev/urandom | head -c2) && wp db export --path=/usr/src/wordpress /var/db/wp.sql
    labels:
      - caddy.servers.client_ip_headers=CF-Connecting-IP X-Forwarded-For
      - caddy_0.tls=internal
      - 'caddy_0.reverse_proxy={{upstreams 80}}'
  mariadb:
    container_name: SITE_NAME-mariadb
    image: 'yobasystems/alpine-mariadb:11'
    # image: jbergstroem/mariadb-alpine
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: '${SERVICE_USER_MARIADB}'
      MYSQL_PASSWORD: '${SERVICE_PASSWORD_MARIADB}'
      MYSQL_ROOT_PASSWORD: '${SERVICE_PASSWORD_MARIADB}'
    volumes:
      - 'sock:/var/run/mysqld'
      - 'db:/var/lib/mysql'
      - '/etc/coolify-setup/mariadb/my.cnf:/etc/my.cnf'
      - '/etc/coolify-setup/mariadb/db-entrypoint.sh:/scripts/run.sh'
  valkey:
    container_name: SITE_NAME-valkey
    image: 'valkey/valkey:8-alpine'
    restart: unless-stopped
    command: sh -c "mkdir -p /tmp/sock && rm -f /tmp/sock/valkey.sock && valkey-server /usr/local/etc/valkey/valkey.conf"
    volumes:
      - '/etc/coolify-setup/valkey/valkey.conf:/usr/local/etc/valkey/valkey.conf'
      - 'sock:/tmp/sock'
volumes:
  db: null
  sock: null
